import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from "@/lib/utils";
import { GitHubUserBadge } from "@/components/github/GitHubUserBadge";
import { Badge } from "@/components/ui/badge";
import { CalendarIcon, CodeIcon, EditIcon, FileIcon, GithubIcon } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
export function ProjectDetails({ project, isGithubConnected, githubUsername, className }) {
    const hasGitHubRepo = !!project.github_repo;
    return (_jsx("div", { className: cn("p-4", className), children: _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx("h3", { className: "text-xl font-medium text-neon-blue", children: project.name }), _jsx("button", { className: "text-gray-400 hover:text-neon-blue", children: _jsx(EditIcon, { className: "h-4 w-4" }) })] }), _jsx("p", { className: "text-sm text-gray-300", children: project.description || "No description provided" })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-400", children: [_jsx(CalendarIcon, { className: "h-4 w-4 text-neon-blue/70" }), _jsxs("span", { children: ["Last modified ", formatDistanceToNow(new Date(project.lastModified), { addSuffix: true })] })] }), hasGitHubRepo && (_jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-400", children: [_jsx(GithubIcon, { className: "h-4 w-4 text-neon-blue/70" }), _jsx("span", { children: project.github_repo }), isGithubConnected && githubUsername && (_jsx(GitHubUserBadge, { username: githubUsername }))] })), project.language && (_jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-400", children: [_jsx(CodeIcon, { className: "h-4 w-4 text-neon-blue/70" }), _jsxs("span", { children: ["Primary language: ", project.language] })] })), project.files_count && (_jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-400", children: [_jsx(FileIcon, { className: "h-4 w-4 text-neon-blue/70" }), _jsxs("span", { children: [project.files_count, " files"] })] }))] }), _jsxs("div", { className: "pt-4 border-t border-neon-blue/10", children: [_jsx("h4", { className: "text-sm font-medium text-neon-blue/90 mb-2", children: "Project Status" }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: "outline", className: "bg-neon-blue/10 text-neon-blue border-neon-blue/30", children: "Active" }), hasGitHubRepo && (_jsx(Badge, { variant: "outline", className: "bg-neon-pink/10 text-neon-pink border-neon-pink/30", children: "GitHub Synced" }))] })] })] }) }));
}
