import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { GithubIcon } from "lucide-react";
import { GitHubUserBadge } from "@/components/github/GitHubUserBadge";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
export function GitHubConnectionSection({ isConnected, isChecking, connectionStatus, username, onConnect, onDisconnect, className }) {
    // Determine if the connection is in the connecting state
    const isConnecting = isChecking || connectionStatus.status === 'connecting';
    return (_jsx("div", { className: cn("p-4 border-b border-neon-blue/20", "bg-gradient-to-r from-dark-lighter/30 to-dark-lighter/10", className), children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(GithubIcon, { className: "h-5 w-5 text-neon-blue" }), _jsx("span", { className: "text-sm font-medium text-neon-blue/90", children: "GitHub" })] }), isConnected ? (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(GitHubUserBadge, { username: username }), _jsx(TooltipProvider, { children: _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsxs("button", { onClick: onDisconnect, className: "relative flex items-center justify-center h-6 w-6 rounded-full bg-red-500 hover:bg-red-600 transition-colors", "aria-label": "Disconnect GitHub", children: [_jsx("span", { className: "absolute inset-0 rounded-full animate-pulse bg-red-500/50" }), _jsx("span", { className: "absolute inset-0 rounded-full shadow-[0_0_8px_theme(colors.red.500)] animate-pulse" })] }) }), _jsx(TooltipContent, { className: "bg-dark-lighter/90 border-neon-pink/30 text-neon-pink shadow-md shadow-neon-pink/20", children: "Click to disconnect GitHub" })] }) })] })) : (_jsx(Button, { variant: "outline", size: "sm", disabled: isConnecting, onClick: onConnect, className: "h-7 text-xs border-neon-blue text-neon-blue hover:bg-neon-blue/10 hover:shadow-[0_0_8px_theme(colors.neon.blue)]", children: isConnecting ? 'Connecting...' : 'Connect' }))] }) }));
}
