import React, { useEffect, useState } from 'react';
import { Card } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Loader2 } from 'lucide-react';

interface LivePreviewProps {
  files: Record<string, string>;
  activeFile?: string;
}

export const LivePreview = ({ files, activeFile }: LivePreviewProps) => {
  const [previewUrl, setPreviewUrl] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Create StackBlitz project configuration
    const project = {
      files,
      title: 'Live Preview',
      description: 'Generated by AI Assistant',
      template: 'vite',
      settings: {
        compile: { clearConsole: false }
      }
    };

    // Generate StackBlitz URL
    const params = new URLSearchParams({
      embed: '1',
      file: activeFile || 'src/App.tsx',
      hideNavigation: '1',
      theme: 'dark'
    });

    const url = `https://stackblitz.com/edit/react-ts-preview?${params}`;
    setPreviewUrl(url);
    setIsLoading(false);
  }, [files, activeFile]);

  return (
    <Card className="h-full">
      <Tabs defaultValue="preview" className="w-full h-full">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="preview">Live Preview</TabsTrigger>
          <TabsTrigger value="stackblitz">StackBlitz</TabsTrigger>
        </TabsList>
        <TabsContent value="preview" className="h-[calc(100%-40px)]">
          {isLoading ? (
            <div className="flex items-center justify-center h-full">
              <Loader2 className="h-8 w-8 animate-spin" />
            </div>
          ) : (
            <iframe
              src={previewUrl}
              className="w-full h-full border-0"
              title="Live Preview"
              allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
              sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
            />
          )}
        </TabsContent>
        <TabsContent value="stackblitz" className="h-[calc(100%-40px)]">
          <iframe
            src={`${previewUrl}&view=editor`}
            className="w-full h-full border-0"
            title="StackBlitz Editor"
          />
        </TabsContent>
      </Tabs>
    </Card>
  );
};