import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { AlertCircle, Github, ExternalLink } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
export function GitHubConnectDialog({ open, onOpenChange, onConnect, connectionStatus, errorMessage }) {
    // Determine if we're in connecting state
    const isConnecting = connectionStatus === 'connecting';
    // Determine error state
    const isError = connectionStatus === 'error';
    return (_jsx(Dialog, { open: open, onOpenChange: onOpenChange, children: _jsxs(DialogContent, { className: "sm:max-w-[425px]", children: [_jsxs(DialogHeader, { children: [_jsxs(DialogTitle, { className: "flex items-center gap-2", children: [_jsx(Github, { className: "h-5 w-5" }), "Connect to GitHub"] }), _jsx(DialogDescription, { children: "Connect your GitHub account to enable repository creation and synchronization." })] }), _jsxs("div", { className: "space-y-4 py-4", children: [_jsxs("div", { className: "text-center pb-2", children: [_jsx(Button, { variant: "outline", className: "w-full", onClick: onConnect, disabled: isConnecting, children: isConnecting ? (_jsxs(_Fragment, { children: [_jsx("div", { className: "h-4 w-4 mr-2 animate-spin rounded-full border-2 border-current border-t-transparent" }), "Connecting..."] })) : (_jsxs(_Fragment, { children: [_jsx(Github, { className: "h-4 w-4 mr-2" }), "Connect with GitHub"] })) }), _jsx("p", { className: "text-xs text-muted-foreground mt-2", children: "This will redirect you to GitHub for authorization" })] }), errorMessage && isError && (_jsxs(Alert, { variant: "destructive", className: "bg-red-500/10 text-red-500", children: [_jsx(AlertCircle, { className: "h-4 w-4" }), _jsx(AlertDescription, { children: errorMessage })] })), _jsxs("div", { className: "rounded-md border p-3", children: [_jsx("h4", { className: "text-sm font-medium mb-2", children: "What this allows:" }), _jsxs("ul", { className: "text-sm space-y-1 text-muted-foreground", children: [_jsx("li", { children: "\u2022 Creating repositories for your projects" }), _jsx("li", { children: "\u2022 Syncing code changes automatically" }), _jsx("li", { children: "\u2022 Collaborating with team members" })] })] })] }), _jsx(DialogFooter, { children: _jsxs("div", { className: "w-full flex justify-between items-center", children: [_jsxs("a", { href: "https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps", target: "_blank", rel: "noopener noreferrer", className: "text-xs text-muted-foreground hover:text-neon-blue flex items-center gap-1", children: [_jsx(ExternalLink, { className: "h-3 w-3" }), "Learn about GitHub OAuth"] }), _jsx(Button, { variant: "ghost", onClick: () => onOpenChange(false), children: "Cancel" })] }) })] }) }));
}
