import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
export function APIKeyCardContent({ config }) {
    return (_jsxs(CardContent, { children: [_jsxs("div", { className: "grid grid-cols-2 gap-4 text-sm", children: [_jsxs("div", { children: [_jsx("div", { className: "font-medium mb-1", children: "Features" }), _jsx("div", { className: "flex flex-wrap gap-1", children: config.feature_bindings && config.feature_bindings.length > 0 ? (config.feature_bindings.map((feature, idx) => (_jsx(Badge, { variant: "outline", className: "capitalize", children: feature.replace('_', ' ') }, idx)))) : (_jsx("span", { className: "text-muted-foreground", children: "No features assigned" })) })] }), _jsxs("div", { children: [_jsx("div", { className: "font-medium mb-1", children: "Settings" }), _jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "RAG:" }), _jsx(Badge, { variant: "secondary", className: "capitalize", children: config.rag_preference || 'supabase' })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "Planning:" }), _jsx(Badge, { variant: "secondary", className: "capitalize", children: config.planning_mode || 'basic' })] })] })] })] }), config.usage_metrics && _jsx(APIKeyCardMetrics, { metrics: config.usage_metrics })] }));
}
function APIKeyCardMetrics({ metrics }) {
    return (_jsxs("div", { className: "mt-4 pt-4 border-t", children: [_jsx("div", { className: "font-medium mb-2", children: "Usage Metrics" }), _jsxs("div", { className: "grid grid-cols-3 gap-3 text-xs", children: [_jsxs("div", { className: "flex flex-col p-2 bg-muted/30 rounded-md", children: [_jsx("span", { className: "text-muted-foreground", children: "Total Calls" }), _jsx("span", { className: "font-medium text-sm", children: metrics.total_calls || 0 })] }), _jsxs("div", { className: "flex flex-col p-2 bg-muted/30 rounded-md", children: [_jsx("span", { className: "text-muted-foreground", children: "Monthly Usage" }), _jsx("span", { className: "font-medium text-sm", children: metrics.monthly_usage || 0 })] }), _jsxs("div", { className: "flex flex-col p-2 bg-muted/30 rounded-md", children: [_jsx("span", { className: "text-muted-foreground", children: "Remaining" }), _jsx("span", { className: "font-medium text-sm", children: metrics.remaining_quota || 'Unlimited' })] })] })] }));
}
