import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Github, Plus, LogOut, User, ChevronDown } from "lucide-react";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { useGitHubConnection } from "@/hooks/github/useGitHubConnection";
export function GitHubAccountCard({ username, accounts, onAddAccount, onDisconnect }) {
    const { setDefaultGitHubAccount } = useGitHubConnection();
    const handleSetDefault = async (accountId) => {
        await setDefaultGitHubAccount(accountId);
    };
    return (_jsxs(Card, { className: "bg-background/30 border border-neon-blue/20 p-3", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("h3", { className: "text-sm font-medium flex items-center gap-1.5", children: [_jsx(Github, { className: "h-4 w-4 text-neon-blue" }), "GitHub Account"] }), _jsxs("div", { className: "flex gap-1", children: [_jsx(Button, { size: "sm", variant: "ghost", className: "h-7 w-7 p-0", onClick: onAddAccount, title: "Add another account", children: _jsx(Plus, { className: "h-3.5 w-3.5" }) }), _jsx(Button, { size: "sm", variant: "ghost", className: "h-7 w-7 p-0 text-red-400 hover:text-red-500 hover:bg-red-500/10", onClick: onDisconnect, title: "Disconnect", children: _jsx(LogOut, { className: "h-3.5 w-3.5" }) })] })] }), _jsxs("div", { className: "bg-background/40 rounded-md p-2 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "h-7 w-7 rounded-full bg-neon-blue/20 flex items-center justify-center", children: _jsx(User, { className: "h-4 w-4 text-neon-blue" }) }), _jsxs("div", { children: [_jsxs("p", { className: "text-sm font-medium text-neon-blue", children: ["@", username] }), _jsx("p", { className: "text-xs text-muted-foreground", children: "Current account" })] })] }), accounts.length > 1 && (_jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsx(Button, { variant: "ghost", size: "sm", className: "h-7 px-2", children: _jsx(ChevronDown, { className: "h-3.5 w-3.5" }) }) }), _jsxs(DropdownMenuContent, { align: "end", className: "w-48", children: [_jsx(DropdownMenuLabel, { children: "Switch Account" }), _jsx(DropdownMenuSeparator, {}), accounts.map(account => (_jsxs(DropdownMenuItem, { disabled: account.default, onClick: () => handleSetDefault(account.id), className: account.default ? "bg-muted/50 text-neon-blue font-medium" : "", children: [_jsx(Github, { className: "h-4 w-4 mr-2" }), "@", account.username, account.default && _jsx("span", { className: "ml-auto text-xs opacity-70", children: "Current" })] }, account.id)))] })] }))] })] }));
}
