import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Key, MessageSquare, Settings, Zap, Save, Shield, Bell } from "lucide-react";
import { GeneralSettings } from "./GeneralSettings";
import { PrivacySettings } from "./PrivacySettings";
import { UISettings } from "./UISettings";
import { AdvancedSettings } from "./AdvancedSettings";
import { NotificationSettings } from "./NotificationSettings";
import { APIKeyManagement } from "../api/APIKeyManagement";
import { Button } from "@/components/ui/button";
export const ChatSettingsTabs = ({ activeTab, setActiveTab, settings, handleSettingChange, handleClearHistory, handleSave }) => {
    return (_jsxs(Tabs, { value: activeTab, onValueChange: setActiveTab, className: "w-full", children: [_jsxs(TabsList, { className: "grid grid-cols-2 md:grid-cols-6 gap-1", children: [_jsxs(TabsTrigger, { value: "general", className: "flex items-center gap-2", children: [_jsx(MessageSquare, { className: "h-4 w-4" }), "General"] }), _jsxs(TabsTrigger, { value: "api_keys", className: "flex items-center gap-2", children: [_jsx(Key, { className: "h-4 w-4" }), "API Keys"] }), _jsxs(TabsTrigger, { value: "privacy", className: "flex items-center gap-2", children: [_jsx(Shield, { className: "h-4 w-4" }), "Privacy"] }), _jsxs(TabsTrigger, { value: "ui", className: "flex items-center gap-2", children: [_jsx(Settings, { className: "h-4 w-4" }), "UI"] }), _jsxs(TabsTrigger, { value: "advanced", className: "flex items-center gap-2", children: [_jsx(Zap, { className: "h-4 w-4" }), "Advanced"] }), _jsxs(TabsTrigger, { value: "notifications", className: "flex items-center gap-2", children: [_jsx(Bell, { className: "h-4 w-4" }), "Notifications"] })] }), _jsx(TabsContent, { value: "api_keys", className: "space-y-4 pt-4", children: _jsx(APIKeyManagement, {}) }), _jsx(TabsContent, { value: "general", className: "space-y-4 pt-4", children: _jsx(GeneralSettings, { settings: settings, handleSettingChange: handleSettingChange }) }), _jsx(TabsContent, { value: "privacy", className: "space-y-4 pt-4", children: _jsx(PrivacySettings, { settings: settings, handleSettingChange: handleSettingChange, handleClearHistory: handleClearHistory }) }), _jsx(TabsContent, { value: "ui", className: "space-y-4 pt-4", children: _jsx(UISettings, { settings: settings, handleSettingChange: handleSettingChange }) }), _jsx(TabsContent, { value: "advanced", className: "space-y-4 pt-4", children: _jsx(AdvancedSettings, { settings: settings, handleSettingChange: handleSettingChange }) }), _jsx(TabsContent, { value: "notifications", className: "space-y-4 pt-4", children: _jsx(NotificationSettings, { settings: settings, handleSettingChange: handleSettingChange }) }), _jsx("div", { className: "flex justify-end mt-6", children: _jsxs(Button, { onClick: handleSave, className: "admin-primary-button group", children: [_jsx(Save, { className: "h-4 w-4 mr-2 transition-transform group-hover:scale-110" }), "Save Settings"] }) })] }));
};
