import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { useSettingsStore } from "@/stores/settings";
export function NotificationSettings() {
    const { notifications, updateNotifications } = useSettingsStore((state) => ({
        notifications: state.notifications,
        updateNotifications: state.updateNotifications,
    }));
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-medium", children: "Notification Preferences" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Configure how you want to receive notifications." })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "space-y-0.5", children: [_jsx(Label, { htmlFor: "email-notifications", children: "Email Notifications" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Receive notifications via email" })] }), _jsx(Switch, { id: "email-notifications", checked: notifications.email, onCheckedChange: (checked) => updateNotifications({ email: checked }) })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "space-y-0.5", children: [_jsx(Label, { htmlFor: "push-notifications", children: "Push Notifications" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Receive push notifications in your browser" })] }), _jsx(Switch, { id: "push-notifications", checked: notifications.push, onCheckedChange: (checked) => updateNotifications({ push: checked }) })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "space-y-0.5", children: [_jsx(Label, { htmlFor: "marketing-notifications", children: "Marketing Updates" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Receive updates about new features and promotions" })] }), _jsx(Switch, { id: "marketing-notifications", checked: notifications.marketing, onCheckedChange: (checked) => updateNotifications({ marketing: checked }) })] })] })] }));
}
