// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewjisqyvspdvhyppkhnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3amlzcXl2c3Bkdmh5cHBraG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMzk2NTksImV4cCI6MjA0OTYxNTY1OX0.N_-8X0NPm7gho5-YBuKseINZQhqgFiptUpc-tpQBraQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);