// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piblrbualszlacmlgmbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpYmxyYnVhbHN6bGFjbWxnbWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NTEzODYsImV4cCI6MjA0OTUyNzM4Nn0.JdVAGE1BkSXQ8FB-kWXWBDLEKQAxkh8roX7xaGzdlQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);