// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deksjwrdczcsnryjohzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRla3Nqd3JkY3pjc25yeWpvaHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NTA4MDksImV4cCI6MjA1NTIyNjgwOX0.9GaXQnHZPUoVQwLQpu2v9bbYr8xqO8sSQczIlmzovYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);